package:
  name: hazy
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX
    - HAZY_C_PREFIX

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - cmake
    - numpy
    - scipy

  run:
    - numpy
    - scipy
    - python
    - vs2015_runtime  # [win]

about:
  summary: An example project built with pybind11.
  license_file: LICENSE
