#!/bin/bash
set -e

COOCCURRENCE_FILE=$1
SEED=$2
COOCCUR_DIR=$(dirname $COOCCURRENCE_FILE)

COOCCURRENCE_SHUF_FILE=$COOCCUR_DIR/text8_96M_cooccurrence_minCount_5_ws_15.shuf_$SEED.bin
BUILDDIR=build
VERBOSE=2
MEMORY=500.0

echo "$ $BUILDDIR/shuffle -seed $SEED -memory $MEMORY -verbose $VERBOSE < $COOCCURRENCE_FILE > $COOCCURRENCE_SHUF_FILE"
$BUILDDIR/shuffle -seed $SEED -memory $MEMORY -verbose $VERBOSE < $COOCCURRENCE_FILE > $COOCCURRENCE_SHUF_FILE
